name: Mirror Docker Hub → GHCR

on:
  schedule:
    - cron: "0 6 1 * *" # 1er de chaque mois à 6h UTC
  workflow_dispatch:
    inputs:
      elk_version:
        description: "Version de la stack Elastic"
        required: false
        default: "9.0.0"

permissions:
  contents: read
  packages: write

jobs:
  mirror:
    name: Mirror images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v4

      - name: Login GHCR
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Mirror images (multi-arch)
        env:
          ELK_VERSION: ${{ inputs.elk_version || '9.0.0' }}
        run: bash .github/scripts/mirror-images.sh

#      - name: Notify Discord — succès
#        if: success()
#        uses: sarisia/actions-status-discord@v1
#        with:
#          webhook: ${{ secrets.DISCORD_WEBHOOK_INFRA }}
#          status: success
#          title: "✅ Mirror Docker Hub → GHCR réussi"
#
#      - name: Notify Discord — échec
#        if: failure()
#        uses: sarisia/actions-status-discord@v1
#        with:
#          webhook: ${{ secrets.DISCORD_WEBHOOK_INFRA }}
#          status: failure
#          title: "❌ Mirror Docker Hub → GHCR échoué"
#          color: 0xFF0000
